### ISSUE TITLE
Websocket connection issue when using PurpleHat

### ISSUE THREAD

**Issue by aaron9589** [tanner87661/IoTTStick#47] opened 2023-08-26 10:44 UTC
Firmware Version: 1.6.3
Connection Type: WiThrottle Client
HAT: PurpleHat
Browser: Firefox
OS: Ubuntu

Am trying to run the speed matching tool on my stick, however for some reason I get a web socket timeout right before it completes the testing.

If I do a calibration using a max speed of 10km/h, 10 speed steps, 10 throttle steps - it loads ok.

If I do the same calibration using values of 80kmh, 80 speed steps, 126 throttle steps (NCE) - it times out at the very end (screenshot below)

![image](https://github.com/tanner87661/IoTTStick/assets/1221799/d6ef6d34-72a4-440b-9e5a-c76a659e0859)

 Looking in the web developer console I see the web socket connection close, and the bottom panel (with the blue graph) doesn't load.

Any ideas what may be causing it?

**Comment by aaron9589** [comment] 2023-08-26 11:29
did another test tonight, got some more info.

Console dump:

[console-export-2023-8-26_21-21-17.txt](https://github.com/tanner87661/IoTTStick/files/12445239/console-export-2023-8-26_21-21-17.txt)

in the console log, you can see it failing and dropping the web socket and reconnecting - and the page ends up being unresponsive after that.

If I compare timestamps in the web socket with received data, this request is received right before the error, and has a few odd characters at the end of the string:
```json
{"Cmd":"SpeedTableData","Data":{"Dir":false,"Mode":0,"CurrStep":86,"SlotNr":1,"NumSteps":127,"fw":[0,2.701122761,4.580702305,6.935476303,10.35271931,13.36022472,17.01188278,21.36785126,25.86894035,31.69150734,34.69936752,40.20102692,46.16449356,49.36275482,53.18253326,57.15507889,63.66621399,63.99951935,67.84176636,71.99633789,74.06533813,77.89655304,80.84039307,84.65609741,88.29983521,90.86221313,95.89411926,97.12915802,99.90727997,105.392067,107.8302536,114.4875717,116.7615738,119.3237228,127.9502487,126.5179749,129.5865936,133.4684601,136.6468811,139.1513519,140.700882,142.3325958,147.9250031,153.87854,159.1052399,159.0183105,164.5879059,166.3733521,171.6068115,174.0254822,173.5295868,175.9178467,182.272995,189.7569885,192.7520142,194.4931793,197.9884949,203.3379517,205.0877228,207.2387085,211.5190125,216.9585724,220.31073,220.7253876,229.6643219,235.6886597,235.8377686,0,0,0,0,253.9034271,0,0,0,0,261.5869446,0,0,0,0,282.8605042,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"bw":[0,3.225928783,5.073324203,7.563786507,9.909949303,12.98509407,16.44610023,20.33689308,24.9893055,30.07433891,33.84439087,39.52126694,44.84172058,48.04472351,52.52362442,55.94034958,59.64300919,63.96393585,64.03791809,70.74885559,73.64017487,76.34868622,79.47932434,83.49713898,87.37646484,88.95101166,91.86249542,94.57391357,98.79779053,103.3178482,106.8720474,111.8055267,113.69767,116.0004883,122.1070633,122.9997711,127.0571518,130.0296478,134.0865784,135.4343262,137.0388489,140.5098572,144.5483398,149.2180023,153.4167786,156.2921295,161.6012115,162.2043304,165.2277832,169.2160034,169.7692719,172.8039551,177.3218079,181.5684509,184.87117,192.579895,191.0441589,203.3286896,200.4568329,202.2395477,206.9701996,205.8092194,209.3774872,217.0464935,220.6032867,224.058197,235.5728607,237.1945496,0,0,0,0,253.9304352,0,0,0,0,264.6795349,0,0,0,0,279.1464844,0,0,0,0,295.7178955,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]$y
```

not sure if this is of use or not, let me know if there is anything else I can grab that may help

**Comment by tanner87661** [comment] 2023-08-26 13:02
Hi Aaron

 

Thanks for the notification. I see you are using Ubuntu with Firefox. Not familiar with Ubuntu, is it possible to use a chromium based browser, as this is what I recommend, and see if the problem persists?

 

I will see if I can make it more error proof in case the websock reconnects so that the page does not become unresponsive. The speed matching process runs entirely on the stick, so it should not be affected, but of course it would be nice to get the data after reconnection 😉

Hans  

 

From: aaron-s ***@***.***> 
Sent: Saturday, August 26, 2023 6:45 AM
To: tanner87661/IoTTStick ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tanner87661/IoTTStick] Websocket connection issue when using PurpleHat (Issue #47)

 

Firmware Version: 1.6.3
Connection Type: WiThrottle Client
HAT: PurpleHat
Browser: Firefox
OS: Ubuntu

Am trying to run the speed matching tool on my stick, however for some reason I get a web socket timeout right before it completes the testing.

If I do a calibration using a max speed of 10km/h, 10 speed steps, 10 throttle steps - it loads ok.

If I do the same calibration using values of 80kmh, 80 speed steps, 126 throttle steps (NCE) - it times out at the very end (screenshot below)

 <https://user-images.githubusercontent.com/1221799/263459368-d6ef6d34-72a4-440b-9e5a-c76a659e0859.png> 

Looking in the web developer console I see the web socket connection close, and the bottom panel (with the blue graph) doesn't load.

Any ideas what may be causing it?

**Comment by aaron9589** [comment] 2023-08-26 13:08
Hey Hans,

sorry should have mentioned - yep am using a Chromium-based browser in Ubuntu. Tried on my Mac as well and seem to get the same  result. Not sure if that additional data that is at the end of the json string is causing it? or where that actually came from. Hopefully you can replicate on your side and see the same issue. Appreciate you looking into it!

-Aaron.

**Comment by aaron9589** [comment] 2023-09-06 12:47
Hey @tanner87661 did you see those junk characters at the end of the JSON string? That happened right before the socket disconnected so am wondering if there are two issues - one caused by that JSON string and whenever websockets drops out and a new connection is established

**Comment by tanner87661** [comment] 2023-09-08 01:15
Hi Aaron

 

Yes, I saw it, it strange. But so far I did not have a chance to look into it. I assume it’s an issue with not clearing the buffer when reconnecting. We’ll see.

 

Best wishes

Hans

**Comment by tanner87661** [comment] 2023-11-24 02:30
Please have a look at 1.6.5 to see if the problem persists. I'm not able to replicate, but made some changes that may improve the communication.

**Comment by aaron9589** [comment] 2023-12-31 10:45
Hey Hans have updated but the issue still persists - although its a slightly different error. This may be because I'm using Chrome rather than Firefox.

I find the issue consistently occurs when I choose a target max speed above 50. 

I tried using Speed Magic using a max speed of 20/30/40 and 50 - no issues. 

Once I set it to 60 or above, it gets to around speed step 70 and then comes up with a WebSockets error and times out. From here, the graph resets to nothing, and the engine continues to cycle back and forth until I abort the test.

<img width="1295" alt="image" src="https://github.com/tanner87661/IoTTStick/assets/1221799/850b99f5-8a12-4618-abd8-70fbde16ec1b">

---

Other things I've tried:

 - Different Operating System/Browser Combinations across multiple devices
 - Changed Wireless networks
 - Different Roster Files including a generic NMRA one from JMRI

--- 

Did some more testing with the websocket console open, it seems to get to a certain size and them bomb out:
![Screenshot_20240101_133232](https://github.com/tanner87661/IoTTStick/assets/1221799/b1527c1b-8186-4a81-89d8-9c958a9f6bf4)

**Comment by aaron9589** [comment] 2024-04-06 01:30
hey @tanner87661 I think the key thing is the size of the websocket payload exceeding 2000 bytes. I've had multiple instances now where it gets to 199* and consistently fails when the packet exceeds 2000 bytes:
![image](https://github.com/tanner87661/IoTTStick/assets/1221799/f0412eb1-3a62-4df0-8d53-34aedafb14c5)
![image](https://github.com/tanner87661/IoTTStick/assets/1221799/7a58f5e3-5bcc-4021-abdb-6321507b34aa)

Hopefully this helps you reproduce the problem on your side?

**Comment by tanner87661** [comment] 2024-04-06 02:24
Hi Aaron

 

I think that was very helpful and I found what’s going on.

Please give this a try: https://www.dropbox.com/scl/fi/htdozr3fc79w0zu221nsk/M5Update.zip?rlkey=gkp0zbldi5y3t5mzrs59hd6gz <https://www.dropbox.com/scl/fi/htdozr3fc79w0zu221nsk/M5Update.zip?rlkey=gkp0zbldi5y3t5mzrs59hd6gz&dl=0> &dl=0

Let me know if it works.

 

Thanks

Hans

**Comment by aaron9589** [comment] 2024-04-06 04:08
Hey @tanner87661 gave that one a go, seems like it got stuck on that 2000 byte issue again:

<img width="1440" alt="image" src="https://github.com/tanner87661/IoTTStick/assets/1221799/7f2aa2c9-de86-4b92-8708-6221cab04c39">

**Comment by tanner87661** [comment] 2024-04-07 03:49
Hi Aaron

 

Well, that was disappointing. I thought I found it, but apparently not.

 

Now, here are two more versions to test that hopefully help me figuring out where the problem is. The two version have different buffer sizes, one 1500, the other 2500 bytes for the WS message. I would like to know if you see a change in the size of the WS message where the error is created. It looks it is a problem of incomplete messages received by the browser, which could be caused by a too small buffer.

 

This is the 1500 byte version: https://www.dropbox.com/scl/fi/j5jo9dwzw7z3aasbvii06/M5Update1500.zip?rlkey=rx26yzbgpghu797flyrui45av <https://www.dropbox.com/scl/fi/j5jo9dwzw7z3aasbvii06/M5Update1500.zip?rlkey=rx26yzbgpghu797flyrui45av&dl=0> &dl=0

And this the 2500 bytes: https://www.dropbox.com/scl/fi/k1tazaxzx5lp5h6e100d3/M5Update2500.zip?rlkey=0mhpsu52oplz9o5nbvdmfu2qg <https://www.dropbox.com/scl/fi/k1tazaxzx5lp5h6e100d3/M5Update2500.zip?rlkey=0mhpsu52oplz9o5nbvdmfu2qg&dl=0> &dl=0

 

Please let me know how it looks like.

Thanks for your help.

Hans

**Comment by aaron9589** [comment] 2024-04-08 06:28
Hey Hans,

have had mixed success so far:

- have tried the 2500 byte fix with success - confirming that the WS payload was above 2k and completed, and was able to download the table.
- have tried again subsequently and it gets to ~ speed step 50 and the stops - no more websocket traffic, however the engine goes back and forth. once it ends, the graph gets quite skewed. screenshot below:
<img width="798" alt="image" src="https://github.com/tanner87661/IoTTStick/assets/1221799/d81a2b82-1427-46f9-9045-a42a54e4224d">


I tried reflashing with the 1500 byte file, but for some reason the screen now ends up going blank. I can reflash with 1.6.5 and it all comes back, but can't seem to upgrade to 1.6.6Dev for the 1500 or 2000 byte variants.. any idea what may be causing that?

(am using a M5Stick CPlus 1.1 if that makes a difference)

**Comment by aaron9589** [comment] 2024-04-09 09:30
Not sure whats happening - something weird going on.

- image with v1.6.5 - no issues
- image with v1 of the fix (that didn't work) - no issues
- image with the 1500 or 2000 fix - both firmwares flash, but the screen never resets. I turn off the device and turn it on,, screen doesn't come on,, nothing else appears to be alive, apart from the COM port. Am able to reflash to one of the above 2 firmwares, stick comes on no problem.

**Comment by tanner87661** [comment] 2024-04-09 14:49
Hi Aaron

 

Looks like something was wrong with the memory settings and the spiffs goes to the wrong address.

Here is one that works: https://www.dropbox.com/scl/fi/j5jo9dwzw7z3aasbvii06/M5Update3000.zip?rlkey=rx26yzbgpghu797flyrui45av <https://www.dropbox.com/scl/fi/j5jo9dwzw7z3aasbvii06/M5Update3000.zip?rlkey=rx26yzbgpghu797flyrui45av&dl=0> &dl=0

I have set the buffer size to 3000. Please see how it does.

Hans

**Comment by aaron9589** [comment] 2024-04-10 08:32
hey Hans,

minor improvement, when I flash it now it does a reset (previously the screen would stay on) and I can see the screen backlight - but the screen itself is still black. Previously I had no indication that the screen was on at all. After about 30 seconds the screen goes dark again. Am able to reflash back to v1.6.5 without issue.

-Aaron

**Comment by tanner87661** [comment] 2024-04-10 13:08
Hi Aaron

 

I just reverified the file, it installs a fresh copy on the stick, so I wonder if there is a problem with the installation process. Do you download the zip file and extract it in a new directory and then run the batch file? I worry that maybe during the installation you load somehow parts of one of the other versions.

Please verify.

Hans

**Comment by aaron9589** [comment] 2024-04-10 13:11
Yep can confirm its an entirely new directory, and i use the batch file. Will try a different PC now and report back shortly

**Comment by aaron9589** [comment] 2024-04-10 13:22
OK so on a mac i get the same result. However I've hooked it up to a serial monitor - its definitely alive:

```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13964
load:0x40080400,len:3600
entry 0x400805f0
4
Jpeg file not found
Jpeg file not found
Jpeg file not found
Jpeg file not found
Mon  10-03-24 09:21:08
IoTT Stick Version 1.6.6Dev
UniqueID: 0C 8B 95 A6 FB 8C 
Load 0 bytes from disk
Digitrax Buffer Data File loaded
File /configdata/node.cfg not found
File read error
```

not sure if this is helpful or not

**Comment by tanner87661** [comment] 2024-04-10 13:27
Ok, it does not find the configuration file. Let me find out why.

**Comment by aaron9589** [comment] 2024-04-10 13:29
Thankyou! I just tried erasing the Flash with M5burner and re-applying the file, and I get a slightly different error now:

```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13964
load:0x40080400,len:3600
entry 0x400805f0
4
E (233) SPIFFS: mount failed, -10025
Jpeg file not found
Jpeg file not found
Jpeg file not found
Jpeg file not found
Mon  10-03-24 09:28:22
IoTT Stick Version 1.6.6Dev
UniqueID: 0C 8B 95 A6 FB 8C 
Unable to read Digitrax Buffer Data File
File /configdata/node.cfg not found
File read error
```

**E (233) SPIFFS: mount failed, -10025**

Appreciate your help with debugging this - am hopeful the new firmware will work but having a hard time just getting it to start at present.

**Comment by tanner87661** [comment] 2024-04-10 13:40
Try to modify the batch file. Change 

esptool write_flash 0x00210000 to esptool write_flash 0x00310000

**Comment by aaron9589** [comment] 2024-04-10 13:53
That's done it! its now responding again.

Its just about midnight here so I will try on the layout tomorrow and report back here.. thanks again!

**Comment by aaron9589** [comment] 2024-04-10 14:26
got carried away, ended up trying it. I tried to set my client and hat type, and once I clicked save it would reboot but freeze on the splash screen.

Serial monitor shows this:

```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13964
load:0x40080400,len:3600
entry 0x400805f0
4
Mon  10-03-24 10:15:32
IoTT Stick Version 1.6.6Dev
UniqueID: 0C 8B 95 A6 FB 8C 
Load 1665 bytes from disk
Digitrax Buffer Data File loaded
File read error
```

previous firmwares are still working fine.

the following is a capture of the serial log as I commit the settings for selecting MQTT client and purplehat:

```
[FROM M5Burner] /dev/tty.usbserial-995A0BA0E7 opened.
Writing Config File from FileStr complete 2359 bytes in 3186 ms
Save Digitrax Data to disk
E (169057) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (169057) task_wdt:  - async_tcp (CPU 0/1)
E (169057) task_wdt: Tasks currently running:
E (169057) task_wdt: CPU 0: async_tcp
E (169057) task_wdt: CPU 1: loopTask
E (169057) task_wdt: Aborting.

abort() was called at PC 0x4012df34 on core 0


Backtrace: 0x40084f11:0x3ffbef5c |<-CORRUPTED




ELF file SHA256: 0f4293a824080be5

Rebooting...
4
Mon  10-03-24 10:33:20
IoTT Stick Version 1.6.6Dev
UniqueID: 0C 8B 95 A6 FB 8C 
Load 0 bytes from disk
Digitrax Buffer Data File loaded
File read error
```

**Comment by tanner87661** [comment] 2024-04-10 19:08
Ok, try this. I am currently fighting some setup options for the Stick Plus2, which may have messed up some settings. It looks like only part of the SPIFFS made it into the flash and some files are missing. 

https://www.dropbox.com/scl/fi/htdozr3fc79w0zu221nsk/M5Update.zip?rlkey=gkp0zbldi5y3t5mzrs59hd6gz <https://www.dropbox.com/scl/fi/htdozr3fc79w0zu221nsk/M5Update.zip?rlkey=gkp0zbldi5y3t5mzrs59hd6gz&dl=0> &dl=0

 

Hans

**Comment by aaron9589** [comment] 2024-04-11 01:20
Yep that newest version is now booting, I was able to:

- Configure the IOTTStick
- start a speed magic test

I set the test for 80km/h at speed step 80, using 126 speed steps (NCE throttles)

The websockets payload doesn't seem to exceed 2k at present, the test seems to stop mid way (note the websocket connection does not drop) - I stop seeing that websocket payload growing, and the train stops at its origin.

It seems to stop at Speed Step 57 backwards  -you'll notice the graph always seems to stop at a certain point.

<img width="1440" alt="image" src="https://github.com/tanner87661/IoTTStick/assets/1221799/33fcd6d7-21aa-4cea-980b-8fb6e4f6469d">

then it generates a speed table with a significant skew:

<img width="977" alt="image" src="https://github.com/tanner87661/IoTTStick/assets/1221799/7bcbbaf7-8070-4bae-bc06-2f0b265d2a59">

---

tried in chrome, seems to follow a similar pattern:
<img width="1440" alt="image" src="https://github.com/tanner87661/IoTTStick/assets/1221799/75b03c0f-1313-400c-98c3-2bc951a786e2">


<img width="1440" alt="image" src="https://github.com/tanner87661/IoTTStick/assets/1221799/6a5444e1-12d1-480a-9514-0b3116fd2b15">

**Comment by tanner87661** [comment] 2024-04-11 01:54
Try to make the test track longer. The curve indicates that the test was stopped, which can have two reasons:

*	The loco is not able to reach the target speed. The speed step was increased three times but no significant speed increase was measured
*	The test track is too short and the end is reached at the same speed step like the run before (there is an overlap from run to run and some wait time between the steps to let oscillation of the coupler calm down).

 

But other than that, it looks like it is working now.

Hans

**Comment by aaron9589** [comment] 2024-04-11 09:34
> Try to make the test track longer.

Hey Hans,

Sorry, this was a layer 8 error on my part. I was trying to speed match an engine without a linear speed table.

After re-configuring the speed table, I was able to do a test and pass the 2k payload size without issue:

<img width="1438" alt="image" src="https://github.com/tanner87661/IoTTStick/assets/1221799/49796168-42f3-446b-bb1b-0b87c9c5cf14">

I will do some more tests this evening, but so far everything is looking very good

-Aaron.

**Comment by aaron9589** [comment] 2024-04-12 12:17
Hey Hans,

all going well so far, I've done about 5-6 locos, each with payload sizes in the WS session being under or well above 2k and have not had a problem. Thanks for your help working through this issue, greatly appreciated. Did you want me to close this issue or will you keep it open till you merge the changes in a PR?

**Comment by tanner87661** [comment] 2024-04-12 12:21
Hi Aaron

 

Glad it works and thanks for testing. Thanks to your error report and analysis I was able to find it. 

Please go ahead and close the issue. The bugfix is part of Version 1.6.6 which comes out today or tomorrow.

 

Best wishes

Hans

**Closed as completed** 2024-04-12 13:06 UTC
